name: Build Portfolio & Blog

on: 
  push:
    branches: ["main"]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --output dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}